apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yolo
  namespace: prod
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: yolo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
