version: "3.9"

services:
  frontend:
    image: moataz189/frontend-service:${FRONTEND_IMAGE_TAG}
    ports:
      - "3000:3000"
    depends_on:
      - agent
    env_file:
      - frontend/.env
    networks:
      - polyai-net


  agent:
    image: moataz189/agent-service:${AGENT_IMAGE_TAG}
    ports:
      - "8000:8000"
    depends_on:
      - yolo
      - img-proc-mcp
    env_file:
      - agent/.env
    networks:
      - polyai-net
 
  yolo:
    image: moataz189/yolo-service:${YOLO_IMAGE_TAG}
    ports:
      - "8080:8080"
    env_file:
      - yolo/.env
    networks:
      - polyai-net
   

  img-proc-mcp:
    image: moataz189/img-proc-mcp:${IMG_PROC_MCP_IMAGE_TAG}
    ports:
      - "9000:9000"
    env_file:
      - img-proc-mcp/.env
    networks:
      - polyai-net
  

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - yolo
      - node-exporter
    networks:
      - polyai-net
      - monitoring-net
  

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-net
  

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    networks:
      - monitoring-net


  #add fluent-bit service to the docker-compose file
fluent-bit:
  image: fluent/fluent-bit:4.2.7
  volumes:
    - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    - /var/log/journal:/var/log/journal:ro
    - /run/log/journal:/run/log/journal:ro
    - /etc/machine-id:/etc/machine-id:ro
    - /var/log:/var/log
  restart: unless-stopped
  networks:
    - monitoring-net

volumes:
  grafana-data:
  prometheus-data:

networks:
  polyai-net:
    driver: bridge

  monitoring-net:
    driver: bridge