version: "3.9"

services:
  frontend:
    image: moataz189/frontend-service:${FRONTEND_IMAGE_TAG}
    ports:
      - "3000:3000"
    depends_on:
      - agent
    env_file:
      - frontend/.env
    networks:
      - polyai-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        tag: "frontend"

  agent:
    image: moataz189/agent-service:${AGENT_IMAGE_TAG}
    ports:
      - "8000:8000"
    depends_on:
      - yolo
      - img-proc-mcp
    env_file:
      - agent/.env
    networks:
      - polyai-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        tag: "agent"

  yolo:
    image: moataz189/yolo-service:${YOLO_IMAGE_TAG}
    ports:
      - "8080:8080"
    env_file:
      - yolo/.env
    networks:
      - polyai-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        tag: "yolo"

  img-proc-mcp:
    image: moataz189/img-proc-mcp:${IMG_PROC_MCP_IMAGE_TAG}
    ports:
      - "9000:9000"
    env_file:
      - img-proc-mcp/.env
    networks:
      - polyai-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        tag: "img-proc-mcp"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - yolo
      - node-exporter
    networks:
      - polyai-net
      - monitoring-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        tag: "prometheus"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        tag: "grafana"

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    networks:
      - monitoring-net
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"
        tag: "node-exporter"

  #add fluent-bit service to the docker-compose file
  fluent-bit:
    image: fluent/fluent-bit:4.2.7
    ports:
      - "127.0.0.1:24224:24224"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    restart: unless-stopped
    networks:
      - monitoring-net

volumes:
  grafana-data:
  prometheus-data:

networks:
  polyai-net:
    driver: bridge

  monitoring-net:
    driver: bridge