[OUTPUT]
    Name              s3
    Match             docker.*
    bucket            moataz-polyai-logs-dev
    region            us-east-1

    s3_key_format     /logs/dev/%Y/%m/%d/$TAG[5]/%H%M%S_$UUID.gz
    compression       gzip

    upload_timeout    5m
    total_file_size   5M
    use_put_object    On

    store_dir         /var/log/fluent-bit/s3
    store_dir_limit_size 1G