[SERVICE]
    Flush         5
    Log_Level     info

[INPUT]
    Name          systemd
    Tag           docker.*
    DB            /var/log/flb_journald.db
    Read_From_Tail On

[FILTER]
    Name          rewrite_tag
    Match         docker.*
    Rule          $CONTAINER_TAG ^(.+)$ service.$1 false

[FILTER]
    Name          record_modifier
    Match         service.*
    Record        host ${HOSTNAME}

[OUTPUT]
    Name              s3
    Match             service.*
    bucket            moataz-polyai-logs-dev
    region            us-east-1
    s3_key_format     /logs/$TAG[1]/%Y/%m/%d/%H-%M-%S-$UUID.gz
    compression       gzip
    upload_timeout    60s
    use_put_object    On
    total_file_size   1M