[SERVICE]
    Flush         5
    Log_Level     info

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224

[FILTER]
    Name          record_modifier
    Match         *
    Record        host ${HOSTNAME}

[OUTPUT]
    Name              s3
    Match             docker.*
    bucket            moataz-polyai-logs-prod

    region            us-east-1
    s3_key_format     /logs/$TAG/%Y/%m/%d/%H-%M-%S-$UUID.gz
    compression       gzip
    upload_timeout    60s
    use_put_object    On
    total_file_size   1M