apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "yolo"
        static_configs:
          - targets:
              - "yolo-svc:8080"

      - job_name: "agent"
        static_configs:
          - targets:
              - "agent-svc:8000"
