apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: prod
  labels:
    app: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: moataz189/frontend-service:5e5723daac53d8ad4a6d50b76df0719bb7443233

          ports:
            - containerPort: 3000

          env:
            - name: AGENT_INTERNAL_URL
              value: "http://agent-svc:8000"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/ready
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
