apiVersion: apps/v1
kind: Deployment

metadata:
  name: img-proc-mcp
  namespace: prod
  labels:
    app: img-proc-mcp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: img-proc-mcp

  template:
    metadata:
      labels:
        app: img-proc-mcp

    spec:
      containers:
        - name: img-proc-mcp
          image: moataz189/img-proc-mcp:962723f552b3cd81b5a43f46e3f7de025b34f905

          ports:
            - containerPort: 9000

          env:
            - name: AWS_REGION
              value: "us-east-1"

            - name: S3_BUCKET
              value: "moataz-polyai-images"

            - name: S3_PROCESSED_PREFIX
              value: "processed/"