apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: dev
  labels:
    app: grafana

spec:
  replicas: 1

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      securityContext:
        fsGroup: 472

      containers:
        - name: grafana
          image: grafana/grafana:12.1.0

          ports:
            - containerPort: 3000

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin

            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin123

          volumeMounts:
            # Grafana persistent data
            - name: grafana-data
              mountPath: /var/lib/grafana

            # Prometheus datasource configuration
            - name: grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
              readOnly: true

            # Dashboard provider configuration
            - name: grafana-dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
              readOnly: true

            # Dashboard JSON files
            - name: grafana-agent-dashboard
              mountPath: /var/lib/grafana/dashboards
              readOnly: true

      volumes:
        # Persistent Grafana storage
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pvc

        # Prometheus datasource ConfigMap
        - name: grafana-datasource
          configMap:
            name: grafana-datasource

        # Dashboard provider ConfigMap
        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider

        # agent.json ConfigMap
        - name: grafana-agent-dashboard
          configMap:
            name: grafana-agent-dashboard