name: Deploy Yolo

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev instance
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_INSTANCE_HOST}}
          username: ubuntu
          key: ${{ secrets.DEV_INSTANCE_SSH_KEY }}
          script: |
            cd /home/ubuntu/polyaifursa
            git pull origin dev
            source .venv/bin/activate
            pip install -r services/agent/requirements.txt
            cd services/frontend
            npm install
            npm run build
            sudo cp ../deployments/agent.service /etc/systemd/system/agent.service
            sudo cp ../deployments/frontend.service /etc/systemd/system/frontend.service
            cd ../yolo
            pip install -r torch-requirements.txt
            pip install -r requirements.txt
            sudo systemctl restart yolo
            sudo systemctl status yolo --no-pager
            sudo systemctl daemon-reload
            sudo systemctl enable yolo agent frontend
            sudo systemctl restart yolo agent frontend
            sudo systemctl status agent --no-pager
            sudo systemctl status frontend --no-pager

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Prod instance
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_INSTANCE_HOST }}
          username: ubuntu
          key: ${{ secrets.PROD_INSTANCE_SSH_KEY }}
          script: |
            cd /home/ubuntu/polyaifursa
            source .venv/bin/activate
            pip install -r services/agent/requirements.txt
            pip install -r services/yolo/torch-requirements.txt
            pip install -r services/yolo/requirements.txt

            cd services/frontend
            npm install
            npm run build

            sudo cp ../deployments/agent.service /etc/systemd/system/agent.service
            sudo cp ../deployments/frontend.service /etc/systemd/system/frontend.service

            sudo systemctl daemon-reload
            sudo systemctl enable yolo agent frontend
            sudo systemctl restart yolo agent frontend